# Xcode


trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
